### ISSUE TITLE
Argument comprised from discontinuous spans ?

### ISSUE THREAD

**Issue by thangld201** [ZhaoyueSun/phee-with-chatgpt#1]
Hi @ZhaoyueSun, thank you very much for the works!

I found cases in the PHEE 2.0 dataset cases where argument (entity) is represented by discontinuous span. For example
```
'Four patients who manifested symptoms of the antiepileptic drug (AED) hypersensitivity syndrome during therapy with carbamazepine are reported.', 

{'event_id': 'E1', 'event_type': 'Adverse_event', 'Trigger': {'text': [['symptoms of']], 'start': [[29]], 'entity_id': ['T6']}, 'Subject': {'text': [['Four patients']], 'start': [[0]], 'entity_id': ['T4'], 'Population': {'text': [['Four']], 'start': [[0]], 'entity_id': ['T7']}}, 'Effect': {'text': [['hypersensitivity syndrome']], 'start': [[70]], 'entity_id': ['T3']}, 'Treatment': {'text': [['antiepileptic drug (AED)', 'during therapy with carbamazepine']], 'start': [[45, 96]], 'entity_id': ['T5'], 'Drug': {'text': [['antiepileptic drug (AED)'], ['carbamazepine']], 'start': [[45], [116]], 'entity_id': ['T8', 'T9']}}}
```

Here the `'entity_id': ['T5']` lasts in discontinuous spans. Is this annotation error or due to guidelines ?

**Comment by ZhaoyueSun** [comment]
Hi,

To ensure semantic integrity, discontinuous spans are allowed in annotations. This case is not an error one. However, annotators suffer from inconsistency in ambiguous cases, so another annotator might only annotate "carbamazepine" as the "drug" in a similar situation, though that doesn't often happen for the annotations of "drug".
